---

num_rounds: 10
num_clients: 100
batch_size: 20
num_classes: 10
num_clients_per_round_fit: 10
num_clients_per_round_eval: 25
cpu_count_per_client: 2
gpu_count_per_client: 0.30
config_fit:
    lr: 0.01
    momentum: 0.9
    local_epochs: 1

hydra:
  run:
    dir: /dcs/large/u2238887/flower_simulations/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
